# -*- coding: utf-8 -*-
import sys,time
from PyQt5.QtWidgets import QApplication, QMainWindow

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 800)
        Form.setMinimumSize(QtCore.QSize(600, 800))
        Form.setMaximumSize(QtCore.QSize(600, 800))
        self.runButton = QtWidgets.QPushButton(Form)
        self.runButton.setGeometry(QtCore.QRect(110, 600, 101, 51))
        self.runButton.setObjectName("runButton")
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(400, 600, 101, 51))
        self.exitButton.setObjectName("exitButton")
        self.cleanButton = QtWidgets.QPushButton(Form)
        self.cleanButton.setGeometry(QtCore.QRect(260, 600, 101, 51))
        self.cleanButton.setObjectName("cleanButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 60, 460, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit57 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit57.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit57.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit57.setFont(font)
        self.lineEdit57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit57.setObjectName("lineEdit57")
        self.gridLayout_9.addWidget(self.lineEdit57, 0, 0, 1, 1)
        self.lineEdit58 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit58.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit58.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit58.setFont(font)
        self.lineEdit58.setText("")
        self.lineEdit58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit58.setObjectName("lineEdit58")
        self.gridLayout_9.addWidget(self.lineEdit58, 0, 1, 1, 1)
        self.lineEdit59 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit59.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit59.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit59.setFont(font)
        self.lineEdit59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit59.setObjectName("lineEdit59")
        self.gridLayout_9.addWidget(self.lineEdit59, 0, 2, 1, 1)
        self.lineEdit66 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit66.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit66.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit66.setFont(font)
        self.lineEdit66.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit66.setObjectName("lineEdit66")
        self.gridLayout_9.addWidget(self.lineEdit66, 1, 0, 1, 1)
        self.lineEdit67 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit67.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit67.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit67.setFont(font)
        self.lineEdit67.setText("")
        self.lineEdit67.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit67.setObjectName("lineEdit67")
        self.gridLayout_9.addWidget(self.lineEdit67, 1, 1, 1, 1)
        self.lineEdit68 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit68.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit68.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit68.setFont(font)
        self.lineEdit68.setText("")
        self.lineEdit68.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit68.setObjectName("lineEdit68")
        self.gridLayout_9.addWidget(self.lineEdit68, 1, 2, 1, 1)
        self.lineEdit75 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit75.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit75.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit75.setFont(font)
        self.lineEdit75.setText("")
        self.lineEdit75.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit75.setObjectName("lineEdit75")
        self.gridLayout_9.addWidget(self.lineEdit75, 2, 0, 1, 1)
        self.lineEdit76 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit76.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit76.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit76.setFont(font)
        self.lineEdit76.setText("")
        self.lineEdit76.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit76.setObjectName("lineEdit76")
        self.gridLayout_9.addWidget(self.lineEdit76, 2, 1, 1, 1)
        self.lineEdit77 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit77.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit77.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit77.setFont(font)
        self.lineEdit77.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit77.setObjectName("lineEdit77")
        self.gridLayout_9.addWidget(self.lineEdit77, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 4, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit54 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit54.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit54.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit54.setFont(font)
        self.lineEdit54.setText("")
        self.lineEdit54.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit54.setObjectName("lineEdit54")
        self.gridLayout_8.addWidget(self.lineEdit54, 0, 0, 1, 1)
        self.lineEdit55 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit55.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit55.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit55.setFont(font)
        self.lineEdit55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit55.setObjectName("lineEdit55")
        self.gridLayout_8.addWidget(self.lineEdit55, 0, 1, 1, 1)
        self.lineEdit56 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit56.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit56.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit56.setFont(font)
        self.lineEdit56.setText("")
        self.lineEdit56.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit56.setObjectName("lineEdit56")
        self.gridLayout_8.addWidget(self.lineEdit56, 0, 2, 1, 1)
        self.lineEdit63 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit63.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit63.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit63.setFont(font)
        self.lineEdit63.setText("")
        self.lineEdit63.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit63.setObjectName("lineEdit63")
        self.gridLayout_8.addWidget(self.lineEdit63, 1, 0, 1, 1)
        self.lineEdit64 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit64.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit64.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit64.setFont(font)
        self.lineEdit64.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit64.setObjectName("lineEdit64")
        self.gridLayout_8.addWidget(self.lineEdit64, 1, 1, 1, 1)
        self.lineEdit65 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit65.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit65.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit65.setFont(font)
        self.lineEdit65.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit65.setObjectName("lineEdit65")
        self.gridLayout_8.addWidget(self.lineEdit65, 1, 2, 1, 1)
        self.lineEdit72 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit72.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit72.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit72.setFont(font)
        self.lineEdit72.setText("")
        self.lineEdit72.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit72.setObjectName("lineEdit72")
        self.gridLayout_8.addWidget(self.lineEdit72, 2, 0, 1, 1)
        self.lineEdit73 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit73.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit73.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit73.setFont(font)
        self.lineEdit73.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit73.setObjectName("lineEdit73")
        self.gridLayout_8.addWidget(self.lineEdit73, 2, 1, 1, 1)
        self.lineEdit74 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit74.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit74.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit74.setFont(font)
        self.lineEdit74.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit74.setObjectName("lineEdit74")
        self.gridLayout_8.addWidget(self.lineEdit74, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 3, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit3.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit3.setObjectName("lineEdit3")
        self.gridLayout_2.addWidget(self.lineEdit3, 0, 0, 1, 1)
        self.lineEdit4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit4.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit4.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setText("")
        self.lineEdit4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit4.setObjectName("lineEdit4")
        self.gridLayout_2.addWidget(self.lineEdit4, 0, 1, 1, 1)
        self.lineEdit5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit5.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit5.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setText("")
        self.lineEdit5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit5.setObjectName("lineEdit5")
        self.gridLayout_2.addWidget(self.lineEdit5, 0, 2, 1, 1)
        self.lineEdit12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit12.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit12.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit12.setFont(font)
        self.lineEdit12.setText("")
        self.lineEdit12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit12.setObjectName("lineEdit12")
        self.gridLayout_2.addWidget(self.lineEdit12, 1, 0, 1, 1)
        self.lineEdit13 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit13.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit13.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit13.setFont(font)
        self.lineEdit13.setText("")
        self.lineEdit13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit13.setObjectName("lineEdit13")
        self.gridLayout_2.addWidget(self.lineEdit13, 1, 1, 1, 1)
        self.lineEdit14 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit14.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit14.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit14.setFont(font)
        self.lineEdit14.setText("")
        self.lineEdit14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit14.setObjectName("lineEdit14")
        self.gridLayout_2.addWidget(self.lineEdit14, 1, 2, 1, 1)
        self.lineEdit21 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit21.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit21.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit21.setFont(font)
        self.lineEdit21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit21.setObjectName("lineEdit21")
        self.gridLayout_2.addWidget(self.lineEdit21, 2, 0, 1, 1)
        self.lineEdit22 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit22.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit22.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit22.setFont(font)
        self.lineEdit22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit22.setObjectName("lineEdit22")
        self.gridLayout_2.addWidget(self.lineEdit22, 2, 1, 1, 1)
        self.lineEdit23 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit23.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit23.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit23.setFont(font)
        self.lineEdit23.setText("")
        self.lineEdit23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit23.setObjectName("lineEdit23")
        self.gridLayout_2.addWidget(self.lineEdit23, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit6.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setText("")
        self.lineEdit6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit6.setObjectName("lineEdit6")
        self.gridLayout_3.addWidget(self.lineEdit6, 0, 0, 1, 1)
        self.lineEdit7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit7.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setText("")
        self.lineEdit7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit7.setObjectName("lineEdit7")
        self.gridLayout_3.addWidget(self.lineEdit7, 0, 1, 1, 1)
        self.lineEdit8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit8.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setText("")
        self.lineEdit8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit8.setObjectName("lineEdit8")
        self.gridLayout_3.addWidget(self.lineEdit8, 0, 2, 1, 1)
        self.lineEdit15 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit15.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit15.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit15.setFont(font)
        self.lineEdit15.setText("")
        self.lineEdit15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit15.setObjectName("lineEdit15")
        self.gridLayout_3.addWidget(self.lineEdit15, 1, 0, 1, 1)
        self.lineEdit16 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit16.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit16.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit16.setFont(font)
        self.lineEdit16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit16.setObjectName("lineEdit16")
        self.gridLayout_3.addWidget(self.lineEdit16, 1, 1, 1, 1)
        self.lineEdit17 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit17.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit17.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit17.setFont(font)
        self.lineEdit17.setText("")
        self.lineEdit17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit17.setObjectName("lineEdit17")
        self.gridLayout_3.addWidget(self.lineEdit17, 1, 2, 1, 1)
        self.lineEdit24 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit24.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit24.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit24.setFont(font)
        self.lineEdit24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit24.setObjectName("lineEdit24")
        self.gridLayout_3.addWidget(self.lineEdit24, 2, 0, 1, 1)
        self.lineEdit25 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit25.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit25.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit25.setFont(font)
        self.lineEdit25.setText("")
        self.lineEdit25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit25.setObjectName("lineEdit25")
        self.gridLayout_3.addWidget(self.lineEdit25, 2, 1, 1, 1)
        self.lineEdit26 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit26.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit26.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit26.setFont(font)
        self.lineEdit26.setText("")
        self.lineEdit26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit26.setObjectName("lineEdit26")
        self.gridLayout_3.addWidget(self.lineEdit26, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 4, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit30 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit30.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit30.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit30.setFont(font)
        self.lineEdit30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit30.setObjectName("lineEdit30")
        self.gridLayout_5.addWidget(self.lineEdit30, 0, 0, 1, 1)
        self.lineEdit31 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit31.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit31.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit31.setFont(font)
        self.lineEdit31.setText("")
        self.lineEdit31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit31.setObjectName("lineEdit31")
        self.gridLayout_5.addWidget(self.lineEdit31, 0, 1, 1, 1)
        self.lineEdit32 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit32.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit32.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit32.setFont(font)
        self.lineEdit32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit32.setObjectName("lineEdit32")
        self.gridLayout_5.addWidget(self.lineEdit32, 0, 2, 1, 1)
        self.lineEdit39 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit39.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit39.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit39.setFont(font)
        self.lineEdit39.setText("")
        self.lineEdit39.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit39.setObjectName("lineEdit39")
        self.gridLayout_5.addWidget(self.lineEdit39, 1, 0, 1, 1)
        self.lineEdit40 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit40.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit40.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit40.setFont(font)
        self.lineEdit40.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit40.setObjectName("lineEdit40")
        self.gridLayout_5.addWidget(self.lineEdit40, 1, 1, 1, 1)
        self.lineEdit41 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit41.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit41.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit41.setFont(font)
        self.lineEdit41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit41.setObjectName("lineEdit41")
        self.gridLayout_5.addWidget(self.lineEdit41, 1, 2, 1, 1)
        self.lineEdit48 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit48.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit48.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit48.setFont(font)
        self.lineEdit48.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit48.setObjectName("lineEdit48")
        self.gridLayout_5.addWidget(self.lineEdit48, 2, 0, 1, 1)
        self.lineEdit49 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit49.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit49.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit49.setFont(font)
        self.lineEdit49.setText("")
        self.lineEdit49.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit49.setObjectName("lineEdit49")
        self.gridLayout_5.addWidget(self.lineEdit49, 2, 1, 1, 1)
        self.lineEdit50 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit50.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit50.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit50.setFont(font)
        self.lineEdit50.setText("")
        self.lineEdit50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit50.setObjectName("lineEdit50")
        self.gridLayout_5.addWidget(self.lineEdit50, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 2, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit0.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit0.setFont(font)
        self.lineEdit0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit0.setAutoFillBackground(False)
        self.lineEdit0.setText("")
        self.lineEdit0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit0.setObjectName("lineEdit0")
        self.gridLayout.addWidget(self.lineEdit0, 0, 0, 1, 1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit1.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setText("")
        self.lineEdit1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout.addWidget(self.lineEdit1, 0, 1, 1, 1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit2.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout.addWidget(self.lineEdit2, 0, 2, 1, 1)
        self.lineEdit9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit9.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit9.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit9.setObjectName("lineEdit9")
        self.gridLayout.addWidget(self.lineEdit9, 1, 0, 1, 1)
        self.lineEdit10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit10.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit10.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setText("")
        self.lineEdit10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit10.setObjectName("lineEdit10")
        self.gridLayout.addWidget(self.lineEdit10, 1, 1, 1, 1)
        self.lineEdit11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit11.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit11.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit11.setFont(font)
        self.lineEdit11.setText("")
        self.lineEdit11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit11.setObjectName("lineEdit11")
        self.gridLayout.addWidget(self.lineEdit11, 1, 2, 1, 1)
        self.lineEdit18 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit18.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit18.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit18.setFont(font)
        self.lineEdit18.setText("")
        self.lineEdit18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit18.setObjectName("lineEdit18")
        self.gridLayout.addWidget(self.lineEdit18, 2, 0, 1, 1)
        self.lineEdit19 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit19.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit19.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit19.setFont(font)
        self.lineEdit19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit19.setObjectName("lineEdit19")
        self.gridLayout.addWidget(self.lineEdit19, 2, 1, 1, 1)
        self.lineEdit20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit20.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit20.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit20.setFont(font)
        self.lineEdit20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit20.setObjectName("lineEdit20")
        self.gridLayout.addWidget(self.lineEdit20, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit33 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit33.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit33.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit33.setFont(font)
        self.lineEdit33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit33.setObjectName("lineEdit33")
        self.gridLayout_6.addWidget(self.lineEdit33, 0, 0, 1, 1)
        self.lineEdit34 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit34.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit34.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit34.setFont(font)
        self.lineEdit34.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit34.setObjectName("lineEdit34")
        self.gridLayout_6.addWidget(self.lineEdit34, 0, 1, 1, 1)
        self.lineEdit35 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit35.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit35.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit35.setFont(font)
        self.lineEdit35.setText("")
        self.lineEdit35.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit35.setObjectName("lineEdit35")
        self.gridLayout_6.addWidget(self.lineEdit35, 0, 2, 1, 1)
        self.lineEdit42 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit42.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit42.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit42.setFont(font)
        self.lineEdit42.setText("")
        self.lineEdit42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit42.setObjectName("lineEdit42")
        self.gridLayout_6.addWidget(self.lineEdit42, 1, 0, 1, 1)
        self.lineEdit43 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit43.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit43.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit43.setFont(font)
        self.lineEdit43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit43.setObjectName("lineEdit43")
        self.gridLayout_6.addWidget(self.lineEdit43, 1, 1, 1, 1)
        self.lineEdit44 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit44.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit44.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit44.setFont(font)
        self.lineEdit44.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit44.setObjectName("lineEdit44")
        self.gridLayout_6.addWidget(self.lineEdit44, 1, 2, 1, 1)
        self.lineEdit51 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit51.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit51.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit51.setFont(font)
        self.lineEdit51.setText("")
        self.lineEdit51.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit51.setObjectName("lineEdit51")
        self.gridLayout_6.addWidget(self.lineEdit51, 2, 0, 1, 1)
        self.lineEdit52 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit52.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit52.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit52.setFont(font)
        self.lineEdit52.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit52.setObjectName("lineEdit52")
        self.gridLayout_6.addWidget(self.lineEdit52, 2, 1, 1, 1)
        self.lineEdit53 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit53.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit53.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit53.setFont(font)
        self.lineEdit53.setText("")
        self.lineEdit53.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit53.setObjectName("lineEdit53")
        self.gridLayout_6.addWidget(self.lineEdit53, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 2, 4, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit27 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit27.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit27.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit27.setFont(font)
        self.lineEdit27.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit27.setObjectName("lineEdit27")
        self.gridLayout_4.addWidget(self.lineEdit27, 0, 0, 1, 1)
        self.lineEdit28 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit28.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit28.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit28.setFont(font)
        self.lineEdit28.setText("")
        self.lineEdit28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit28.setObjectName("lineEdit28")
        self.gridLayout_4.addWidget(self.lineEdit28, 0, 1, 1, 1)
        self.lineEdit29 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit29.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit29.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit29.setFont(font)
        self.lineEdit29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit29.setObjectName("lineEdit29")
        self.gridLayout_4.addWidget(self.lineEdit29, 0, 2, 1, 1)
        self.lineEdit36 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit36.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit36.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit36.setFont(font)
        self.lineEdit36.setText("")
        self.lineEdit36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit36.setObjectName("lineEdit36")
        self.gridLayout_4.addWidget(self.lineEdit36, 1, 0, 1, 1)
        self.lineEdit37 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit37.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit37.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit37.setFont(font)
        self.lineEdit37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit37.setObjectName("lineEdit37")
        self.gridLayout_4.addWidget(self.lineEdit37, 1, 1, 1, 1)
        self.lineEdit38 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit38.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit38.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit38.setFont(font)
        self.lineEdit38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit38.setObjectName("lineEdit38")
        self.gridLayout_4.addWidget(self.lineEdit38, 1, 2, 1, 1)
        self.lineEdit45 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit45.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit45.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit45.setFont(font)
        self.lineEdit45.setText("")
        self.lineEdit45.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit45.setObjectName("lineEdit45")
        self.gridLayout_4.addWidget(self.lineEdit45, 2, 0, 1, 1)
        self.lineEdit46 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit46.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit46.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit46.setFont(font)
        self.lineEdit46.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit46.setObjectName("lineEdit46")
        self.gridLayout_4.addWidget(self.lineEdit46, 2, 1, 1, 1)
        self.lineEdit47 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit47.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit47.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit47.setFont(font)
        self.lineEdit47.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit47.setObjectName("lineEdit47")
        self.gridLayout_4.addWidget(self.lineEdit47, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit60 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit60.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit60.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit60.setFont(font)
        self.lineEdit60.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit60.setObjectName("lineEdit60")
        self.gridLayout_7.addWidget(self.lineEdit60, 0, 0, 1, 1)
        self.lineEdit61 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit61.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit61.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit61.setFont(font)
        self.lineEdit61.setText("")
        self.lineEdit61.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit61.setObjectName("lineEdit61")
        self.gridLayout_7.addWidget(self.lineEdit61, 0, 1, 1, 1)
        self.lineEdit62 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit62.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit62.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit62.setFont(font)
        self.lineEdit62.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit62.setObjectName("lineEdit62")
        self.gridLayout_7.addWidget(self.lineEdit62, 0, 2, 1, 1)
        self.lineEdit69 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit69.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit69.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit69.setFont(font)
        self.lineEdit69.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit69.setObjectName("lineEdit69")
        self.gridLayout_7.addWidget(self.lineEdit69, 1, 0, 1, 1)
        self.lineEdit70 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit70.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit70.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit70.setFont(font)
        self.lineEdit70.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit70.setObjectName("lineEdit70")
        self.gridLayout_7.addWidget(self.lineEdit70, 1, 1, 1, 1)
        self.lineEdit71 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit71.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit71.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit71.setFont(font)
        self.lineEdit71.setText("")
        self.lineEdit71.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit71.setObjectName("lineEdit71")
        self.gridLayout_7.addWidget(self.lineEdit71, 1, 2, 1, 1)
        self.lineEdit78 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit78.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit78.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit78.setFont(font)
        self.lineEdit78.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit78.setObjectName("lineEdit78")
        self.gridLayout_7.addWidget(self.lineEdit78, 2, 0, 1, 1)
        self.lineEdit79 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit79.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit79.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit79.setFont(font)
        self.lineEdit79.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit79.setObjectName("lineEdit79")
        self.gridLayout_7.addWidget(self.lineEdit79, 2, 1, 1, 1)
        self.lineEdit80 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit80.setMinimumSize(QtCore.QSize(40, 40))
        self.lineEdit80.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit80.setFont(font)
        self.lineEdit80.setText("")
        self.lineEdit80.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit80.setObjectName("lineEdit80")
        self.gridLayout_7.addWidget(self.lineEdit80, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 2))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 1, 0, 1, 5)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(2, 16777215))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_10.addWidget(self.pushButton, 4, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(2, 16777215))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 4, 3, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(60, 60, 20, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(520, 60, 20, 461))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(70, 50, 461, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(70, 510, 461, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_time = QtWidgets.QLabel(Form)
        self.label_time.setGeometry(QtCore.QRect(100, 540, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")

        self.retranslateUi(Form)
        self.exitButton.clicked.connect(Form.close)
        self.cleanButton.clicked.connect(self.lineEdit77.clear)
        self.cleanButton.clicked.connect(self.lineEdit76.clear)
        self.cleanButton.clicked.connect(self.lineEdit78.clear)
        self.cleanButton.clicked.connect(self.lineEdit75.clear)
        self.cleanButton.clicked.connect(self.lineEdit79.clear)
        self.cleanButton.clicked.connect(self.lineEdit80.clear)
        self.cleanButton.clicked.connect(self.lineEdit74.clear)
        self.cleanButton.clicked.connect(self.lineEdit73.clear)
        self.cleanButton.clicked.connect(self.lineEdit72.clear)
        self.cleanButton.clicked.connect(self.lineEdit63.clear)
        self.cleanButton.clicked.connect(self.lineEdit64.clear)
        self.cleanButton.clicked.connect(self.lineEdit65.clear)
        self.cleanButton.clicked.connect(self.lineEdit66.clear)
        self.cleanButton.clicked.connect(self.lineEdit67.clear)
        self.cleanButton.clicked.connect(self.lineEdit68.clear)
        self.cleanButton.clicked.connect(self.lineEdit69.clear)
        self.cleanButton.clicked.connect(self.lineEdit70.clear)
        self.cleanButton.clicked.connect(self.lineEdit71.clear)
        self.cleanButton.clicked.connect(self.lineEdit54.clear)
        self.cleanButton.clicked.connect(self.lineEdit55.clear)
        self.cleanButton.clicked.connect(self.lineEdit56.clear)
        self.cleanButton.clicked.connect(self.lineEdit57.clear)
        self.cleanButton.clicked.connect(self.lineEdit58.clear)
        self.cleanButton.clicked.connect(self.lineEdit59.clear)
        self.cleanButton.clicked.connect(self.lineEdit60.clear)
        self.cleanButton.clicked.connect(self.lineEdit61.clear)
        self.cleanButton.clicked.connect(self.lineEdit62.clear)
        self.cleanButton.clicked.connect(self.lineEdit53.clear)
        self.cleanButton.clicked.connect(self.lineEdit52.clear)
        self.cleanButton.clicked.connect(self.lineEdit51.clear)
        self.cleanButton.clicked.connect(self.lineEdit50.clear)
        self.cleanButton.clicked.connect(self.lineEdit49.clear)
        self.cleanButton.clicked.connect(self.lineEdit48.clear)
        self.cleanButton.clicked.connect(self.lineEdit47.clear)
        self.cleanButton.clicked.connect(self.lineEdit46.clear)
        self.cleanButton.clicked.connect(self.lineEdit45.clear)
        self.cleanButton.clicked.connect(self.lineEdit36.clear)
        self.cleanButton.clicked.connect(self.lineEdit37.clear)
        self.cleanButton.clicked.connect(self.lineEdit0.clear)
        self.cleanButton.clicked.connect(self.lineEdit1.clear)
        self.cleanButton.clicked.connect(self.lineEdit2.clear)
        self.cleanButton.clicked.connect(self.lineEdit3.clear)
        self.cleanButton.clicked.connect(self.lineEdit4.clear)
        self.cleanButton.clicked.connect(self.lineEdit5.clear)
        self.cleanButton.clicked.connect(self.lineEdit6.clear)
        self.cleanButton.clicked.connect(self.lineEdit7.clear)
        self.cleanButton.clicked.connect(self.lineEdit8.clear)
        self.cleanButton.clicked.connect(self.lineEdit9.clear)
        self.cleanButton.clicked.connect(self.lineEdit10.clear)
        self.cleanButton.clicked.connect(self.lineEdit11.clear)
        self.cleanButton.clicked.connect(self.lineEdit12.clear)
        self.cleanButton.clicked.connect(self.lineEdit13.clear)
        self.cleanButton.clicked.connect(self.lineEdit14.clear)
        self.cleanButton.clicked.connect(self.lineEdit15.clear)
        self.cleanButton.clicked.connect(self.lineEdit16.clear)
        self.cleanButton.clicked.connect(self.lineEdit17.clear)
        self.cleanButton.clicked.connect(self.lineEdit38.clear)
        self.cleanButton.clicked.connect(self.lineEdit39.clear)
        self.cleanButton.clicked.connect(self.lineEdit40.clear)
        self.cleanButton.clicked.connect(self.lineEdit41.clear)
        self.cleanButton.clicked.connect(self.lineEdit42.clear)
        self.cleanButton.clicked.connect(self.lineEdit43.clear)
        self.cleanButton.clicked.connect(self.lineEdit44.clear)
        self.cleanButton.clicked.connect(self.lineEdit18.clear)
        self.cleanButton.clicked.connect(self.lineEdit19.clear)
        self.cleanButton.clicked.connect(self.lineEdit20.clear)
        self.cleanButton.clicked.connect(self.lineEdit27.clear)
        self.cleanButton.clicked.connect(self.lineEdit28.clear)
        self.cleanButton.clicked.connect(self.lineEdit29.clear)
        self.cleanButton.clicked.connect(self.lineEdit30.clear)
        self.cleanButton.clicked.connect(self.lineEdit21.clear)
        self.cleanButton.clicked.connect(self.lineEdit22.clear)
        self.cleanButton.clicked.connect(self.lineEdit31.clear)
        self.cleanButton.clicked.connect(self.lineEdit23.clear)
        self.cleanButton.clicked.connect(self.lineEdit32.clear)
        self.cleanButton.clicked.connect(self.lineEdit24.clear)
        self.cleanButton.clicked.connect(self.lineEdit33.clear)
        self.cleanButton.clicked.connect(self.lineEdit25.clear)
        self.cleanButton.clicked.connect(self.lineEdit34.clear)
        self.cleanButton.clicked.connect(self.lineEdit26.clear)
        self.cleanButton.clicked.connect(self.lineEdit35.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "解数独"))
        self.runButton.setText(_translate("Form", "运算"))
        self.exitButton.setText(_translate("Form", "退出"))
        self.cleanButton.setText(_translate("Form", "清除"))
        self.lineEdit57.setText(_translate("Form", "5"))
        self.lineEdit77.setText(_translate("Form", "9"))
        self.lineEdit55.setText(_translate("Form", "6"))
        self.lineEdit65.setText(_translate("Form", "4"))
        self.lineEdit3.setText(_translate("Form", "3"))
        self.lineEdit22.setText(_translate("Form", "1"))
        self.lineEdit16.setText(_translate("Form", "2"))
        self.lineEdit24.setText(_translate("Form", "5"))
        self.lineEdit32.setText(_translate("Form", "5"))
        self.lineEdit40.setText(_translate("Form", "7"))
        self.lineEdit48.setText(_translate("Form", "2"))
        self.lineEdit2.setText(_translate("Form", "5"))
        self.lineEdit9.setText(_translate("Form", "8"))
        self.lineEdit19.setText(_translate("Form", "7"))
        self.lineEdit33.setText(_translate("Form", "3"))
        self.lineEdit44.setText(_translate("Form", "6"))
        self.lineEdit52.setText(_translate("Form", "8"))
        self.lineEdit27.setText(_translate("Form", "4"))
        self.lineEdit37.setText(_translate("Form", "1"))
        self.lineEdit47.setText(_translate("Form", "3"))
        self.lineEdit62.setText(_translate("Form", "9"))
        self.lineEdit70.setText(_translate("Form", "3"))
        self.lineEdit78.setText(_translate("Form", "7"))


class MyWindow(QMainWindow, Ui_Form):
    
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.setupUi(self)

        self.runButton.clicked.connect(self.assign)
        self.cleanButton.clicked.connect(self.stop_)
    
    def stop_(self):
        
        self.lineEdit0.setStyleSheet("background-color: white")   
        self.lineEdit1.setStyleSheet("background-color: white")   
        self.lineEdit2.setStyleSheet("background-color: white")   
        self.lineEdit3.setStyleSheet("background-color: white")   
        self.lineEdit4.setStyleSheet("background-color: white")   
        self.lineEdit5.setStyleSheet("background-color: white")   
        self.lineEdit6.setStyleSheet("background-color: white")   
        self.lineEdit7.setStyleSheet("background-color: white")   
        self.lineEdit8.setStyleSheet("background-color: white")   
        self.lineEdit9.setStyleSheet("background-color: white")   
        self.lineEdit10.setStyleSheet("background-color: white")   
        self.lineEdit11.setStyleSheet("background-color: white")   
        self.lineEdit12.setStyleSheet("background-color: white")   
        self.lineEdit13.setStyleSheet("background-color: white")   
        self.lineEdit14.setStyleSheet("background-color: white")   
        self.lineEdit15.setStyleSheet("background-color: white")   
        self.lineEdit16.setStyleSheet("background-color: white")   
        self.lineEdit17.setStyleSheet("background-color: white")   
        self.lineEdit18.setStyleSheet("background-color: white")   
        self.lineEdit19.setStyleSheet("background-color: white")   
        self.lineEdit20.setStyleSheet("background-color: white")   
        self.lineEdit21.setStyleSheet("background-color: white")   
        self.lineEdit22.setStyleSheet("background-color: white")   
        self.lineEdit23.setStyleSheet("background-color: white")   
        self.lineEdit24.setStyleSheet("background-color: white")   
        self.lineEdit25.setStyleSheet("background-color: white")   
        self.lineEdit26.setStyleSheet("background-color: white")   
        self.lineEdit27.setStyleSheet("background-color: white")   
        self.lineEdit28.setStyleSheet("background-color: white")   
        self.lineEdit29.setStyleSheet("background-color: white")   
        self.lineEdit30.setStyleSheet("background-color: white")   
        self.lineEdit31.setStyleSheet("background-color: white")   
        self.lineEdit32.setStyleSheet("background-color: white")   
        self.lineEdit33.setStyleSheet("background-color: white")   
        self.lineEdit34.setStyleSheet("background-color: white")   
        self.lineEdit35.setStyleSheet("background-color: white")   
        self.lineEdit36.setStyleSheet("background-color: white")   
        self.lineEdit37.setStyleSheet("background-color: white")   
        self.lineEdit38.setStyleSheet("background-color: white")   
        self.lineEdit39.setStyleSheet("background-color: white")   
        self.lineEdit40.setStyleSheet("background-color: white")   
        self.lineEdit41.setStyleSheet("background-color: white")   
        self.lineEdit42.setStyleSheet("background-color: white")   
        self.lineEdit43.setStyleSheet("background-color: white")   
        self.lineEdit44.setStyleSheet("background-color: white")   
        self.lineEdit45.setStyleSheet("background-color: white")   
        self.lineEdit46.setStyleSheet("background-color: white")   
        self.lineEdit47.setStyleSheet("background-color: white")   
        self.lineEdit48.setStyleSheet("background-color: white")   
        self.lineEdit49.setStyleSheet("background-color: white")   
        self.lineEdit50.setStyleSheet("background-color: white")   
        self.lineEdit51.setStyleSheet("background-color: white")   
        self.lineEdit52.setStyleSheet("background-color: white")   
        self.lineEdit53.setStyleSheet("background-color: white")   
        self.lineEdit54.setStyleSheet("background-color: white")   
        self.lineEdit55.setStyleSheet("background-color: white")   
        self.lineEdit56.setStyleSheet("background-color: white")   
        self.lineEdit57.setStyleSheet("background-color: white")   
        self.lineEdit58.setStyleSheet("background-color: white")   
        self.lineEdit59.setStyleSheet("background-color: white")   
        self.lineEdit60.setStyleSheet("background-color: white")   
        self.lineEdit61.setStyleSheet("background-color: white")   
        self.lineEdit62.setStyleSheet("background-color: white")   
        self.lineEdit63.setStyleSheet("background-color: white")   
        self.lineEdit64.setStyleSheet("background-color: white")   
        self.lineEdit65.setStyleSheet("background-color: white")   
        self.lineEdit66.setStyleSheet("background-color: white")   
        self.lineEdit67.setStyleSheet("background-color: white")   
        self.lineEdit68.setStyleSheet("background-color: white")   
        self.lineEdit69.setStyleSheet("background-color: white")   
        self.lineEdit70.setStyleSheet("background-color: white")   
        self.lineEdit71.setStyleSheet("background-color: white")   
        self.lineEdit72.setStyleSheet("background-color: white")   
        self.lineEdit73.setStyleSheet("background-color: white")   
        self.lineEdit74.setStyleSheet("background-color: white")   
        self.lineEdit75.setStyleSheet("background-color: white")   
        self.lineEdit76.setStyleSheet("background-color: white")   
        self.lineEdit77.setStyleSheet("background-color: white")   
        self.lineEdit78.setStyleSheet("background-color: white")   
        self.lineEdit79.setStyleSheet("background-color: white")   
        self.lineEdit80.setStyleSheet("background-color: white")   
      
    def assign(self):    
        sudoku = [[0 for i in range(9)] for j in range(9)]

        t0 = time.clock()
        if self.lineEdit0.text() != "":
            sudoku[0][0] = int(self.lineEdit0.text()) 
            self.lineEdit0.setStyleSheet("background-color: rgb(228,228,228)")              
        if self.lineEdit1.text() != "":
            sudoku[0][1] = int(self.lineEdit1.text()) 
            self.lineEdit1.setStyleSheet("background-color: rgb(228,228,228)")                         
        if self.lineEdit2.text() != "":
            self.lineEdit2.setStyleSheet("background-color: rgb(228,228,228)")  
            sudoku[0][2] = int(self.lineEdit2.text())                        
        if self.lineEdit3.text() != "":
            self.lineEdit3.setStyleSheet("background-color: rgb(228,228,228)")  
            sudoku[0][3] = int(self.lineEdit3.text())                        
        if self.lineEdit4.text() != "":        
            self.lineEdit4.setStyleSheet("background-color: rgb(228,228,228)")  
            sudoku[0][4] = int(self.lineEdit4.text())                        
        if self.lineEdit5.text() != "":
            self.lineEdit5.setStyleSheet("background-color: rgb(228,228,228)")  
            sudoku[0][5] = int(self.lineEdit5.text())                        
        if self.lineEdit6.text() != "":
            self.lineEdit6.setStyleSheet("background-color: rgb(228,228,228)")  
            sudoku[0][6] = int(self.lineEdit6.text())                        
        if self.lineEdit7.text() != "":
            self.lineEdit7.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[0][7] = int(self.lineEdit7.text())          
        if self.lineEdit8.text() != "": 
            self.lineEdit8.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[0][8] = int(self.lineEdit8.text())                  
        if self.lineEdit9.text() != "":
            self.lineEdit9.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][0] = int(self.lineEdit9.text())                  
        if self.lineEdit10.text() != "":
            self.lineEdit10.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][1] = int(self.lineEdit10.text())                  
        if self.lineEdit11.text() != "":
            self.lineEdit11.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][2] = int(self.lineEdit11.text())                  
        if self.lineEdit12.text() != "":
            self.lineEdit12.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][3] = int(self.lineEdit12.text())                  
        if self.lineEdit13.text() != "":
            self.lineEdit13.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][4] = int(self.lineEdit13.text())                  
        if self.lineEdit14.text() != "":
            self.lineEdit14.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][5] = int(self.lineEdit14.text())                  
        if self.lineEdit15.text() != "":
            self.lineEdit15.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][6] = int(self.lineEdit15.text())                  
        if self.lineEdit16.text() != "":
            self.lineEdit16.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][7] = int(self.lineEdit16.text())                  
        if self.lineEdit17.text() != "":
            self.lineEdit17.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[1][8] = int(self.lineEdit17.text())                  
        if self.lineEdit18.text() != "":
            self.lineEdit18.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][0] = int(self.lineEdit18.text())                  
        if self.lineEdit19.text() != "":
            self.lineEdit19.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][1] = int(self.lineEdit19.text())                  
        if self.lineEdit20.text() != "":
            self.lineEdit20.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][2] = int(self.lineEdit20.text())                  
        if self.lineEdit21.text() != "":
            self.lineEdit21.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][3] = int(self.lineEdit21.text())                  
        if self.lineEdit22.text() != "":
            self.lineEdit22.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][4] = int(self.lineEdit22.text())                  
        if self.lineEdit23.text() != "":
            self.lineEdit23.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][5] = int(self.lineEdit23.text())                  
        if self.lineEdit24.text() != "":
            self.lineEdit24.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][6] = int(self.lineEdit24.text())                  
        if self.lineEdit25.text() != "":
            self.lineEdit25.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][7] = int(self.lineEdit25.text())                  
        if self.lineEdit26.text() != "":
            self.lineEdit26.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[2][8] = int(self.lineEdit26.text())                  
        if self.lineEdit27.text() != "":
            self.lineEdit27.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][0] = int(self.lineEdit27.text())                  
        if self.lineEdit28.text() != "":
            self.lineEdit28.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][1] = int(self.lineEdit28.text())                  
        if self.lineEdit29.text() != "":
            self.lineEdit29.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][2] = int(self.lineEdit29.text())                  
        if self.lineEdit30.text() != "":
            self.lineEdit30.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][3] = int(self.lineEdit30.text())                  
        if self.lineEdit31.text() != "":
            self.lineEdit31.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][4] = int(self.lineEdit31.text())                  
        if self.lineEdit32.text() != "":
            self.lineEdit32.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][5] = int(self.lineEdit32.text())                  
        if self.lineEdit33.text() != "":
            self.lineEdit33.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][6] = int(self.lineEdit33.text())                  
        if self.lineEdit34.text() != "":
            self.lineEdit34.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][7] = int(self.lineEdit34.text())                  
        if self.lineEdit35.text() != "":
            self.lineEdit35.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[3][8] = int(self.lineEdit35.text())                  
        if self.lineEdit36.text() != "":
            self.lineEdit36.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][0] = int(self.lineEdit36.text())                  
        if self.lineEdit37.text() != "":
            self.lineEdit37.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][1] = int(self.lineEdit37.text())                  
        if self.lineEdit38.text() != "":
            self.lineEdit38.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][2] = int(self.lineEdit38.text())                  
        if self.lineEdit39.text() != "":
            self.lineEdit39.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][3] = int(self.lineEdit39.text())                  
        if self.lineEdit40.text() != "":
            self.lineEdit40.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][4] = int(self.lineEdit40.text())                  
        if self.lineEdit41.text() != "":
            self.lineEdit41.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][5] = int(self.lineEdit41.text())                  
        if self.lineEdit42.text() != "":
            self.lineEdit42.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][6] = int(self.lineEdit42.text())                  
        if self.lineEdit43.text() != "":
            self.lineEdit43.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][7] = int(self.lineEdit43.text())                  
        if self.lineEdit44.text() != "":
            self.lineEdit44.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[4][8] = int(self.lineEdit44.text())                  
        if self.lineEdit45.text() != "":
            self.lineEdit45.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][0] = int(self.lineEdit45.text())                  
        if self.lineEdit46.text() != "":
            self.lineEdit46.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][1] = int(self.lineEdit46.text())                  
        if self.lineEdit47.text() != "":
            self.lineEdit47.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][2] = int(self.lineEdit47.text())                  
        if self.lineEdit48.text() != "":
            self.lineEdit48.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][3] = int(self.lineEdit48.text())                  
        if self.lineEdit49.text() != "":
            self.lineEdit49.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][4] = int(self.lineEdit49.text())                  
        if self.lineEdit50.text() != "":
            self.lineEdit50.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][5] = int(self.lineEdit50.text())                  
        if self.lineEdit51.text() != "":
            self.lineEdit51.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][6] = int(self.lineEdit51.text())                  
        if self.lineEdit52.text() != "":
            self.lineEdit52.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][7] = int(self.lineEdit52.text())                  
        if self.lineEdit53.text() != "":
            self.lineEdit53.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[5][8] = int(self.lineEdit53.text())                  
        if self.lineEdit54.text() != "":
            self.lineEdit54.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][0] = int(self.lineEdit54.text())                  
        if self.lineEdit55.text() != "":
            self.lineEdit55.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][1] = int(self.lineEdit55.text())                  
        if self.lineEdit56.text() != "":
            self.lineEdit56.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][2] = int(self.lineEdit56.text())                  
        if self.lineEdit57.text() != "":
            self.lineEdit57.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][3] = int(self.lineEdit57.text())                  
        if self.lineEdit58.text() != "":
            self.lineEdit58.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][4] = int(self.lineEdit58.text())                  
        if self.lineEdit59.text() != "":
            self.lineEdit59.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][5] = int(self.lineEdit59.text())                  
        if self.lineEdit60.text() != "":
            self.lineEdit60.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][6] = int(self.lineEdit60.text())                  
        if self.lineEdit61.text() != "":
            self.lineEdit61.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][7] = int(self.lineEdit61.text())                  
        if self.lineEdit62.text() != "":
            self.lineEdit62.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[6][8] = int(self.lineEdit62.text())                  
        if self.lineEdit63.text() != "":
            self.lineEdit63.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][0] = int(self.lineEdit63.text())                  
        if self.lineEdit64.text() != "":
            self.lineEdit64.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][1] = int(self.lineEdit64.text())                  
        if self.lineEdit65.text() != "":
            self.lineEdit65.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][2] = int(self.lineEdit65.text())                  
        if self.lineEdit66.text() != "":
            self.lineEdit66.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][3] = int(self.lineEdit66.text())                  
        if self.lineEdit67.text() != "":
            self.lineEdit67.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][4] = int(self.lineEdit67.text())                  
        if self.lineEdit68.text() != "":
            self.lineEdit68.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][5] = int(self.lineEdit68.text())                  
        if self.lineEdit69.text() != "":
            self.lineEdit69.setStyleSheet("background-color: rgb(228,228,228)")            
            sudoku[7][6] = int(self.lineEdit69.text())                  
        if self.lineEdit70.text() != "":
            self.lineEdit70.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][7] = int(self.lineEdit70.text())                  
        if self.lineEdit71.text() != "":
            self.lineEdit71.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[7][8] = int(self.lineEdit71.text())                  
        if self.lineEdit72.text() != "":
            self.lineEdit72.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][0] = int(self.lineEdit72.text())                  
        if self.lineEdit73.text() != "":
            self.lineEdit73.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][1] = int(self.lineEdit73.text())                  
        if self.lineEdit74.text() != "":
            self.lineEdit74.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][2] = int(self.lineEdit74.text())                  
        if self.lineEdit75.text() != "":
            self.lineEdit75.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][3] = int(self.lineEdit75.text())                  
        if self.lineEdit76.text() != "":
            self.lineEdit76.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][4] = int(self.lineEdit76.text())                  
        if self.lineEdit77.text() != "":
            self.lineEdit77.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][5] = int(self.lineEdit77.text())                  
        if self.lineEdit78.text() != "":
            self.lineEdit78.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][6] = int(self.lineEdit78.text())                  
        if self.lineEdit79.text() != "":
            self.lineEdit79.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][7] = int(self.lineEdit79.text())                  
        if self.lineEdit80.text() != "":
            self.lineEdit80.setStyleSheet("background-color: rgb(228,228,228)")
            sudoku[8][8] = int(self.lineEdit80.text())      

       


        print(sudoku)
       
        def findNextCellToFill(grid, i, j):
                for x in range(i,9):
                        for y in range(j,9):
                                if grid[x][y] == 0:
                                        return x,y
                for x in range(0,9):
                        for y in range(0,9):
                                if grid[x][y] == 0:
                                        return x,y
                return -1,-1

        def isValid(grid, i, j, e):
                rowOk = all([e != grid[i][x] for x in range(9)])
                if rowOk:
                        columnOk = all([e != grid[x][j] for x in range(9)])
                        if columnOk:                                
                                secTopX, secTopY = 3 *(i//3), 3 *(j//3) 
                                for x in range(secTopX, secTopX+3):
                                        for y in range(secTopY, secTopY+3):
                                                if grid[x][y] == e:
                                                        return False
                                return True
                return False

        def solveSudoku(grid, i=0, j=0):
                i,j = findNextCellToFill(grid, i, j)
                if i == -1:
                        return True
                for e in range(1,10):
                        if isValid(grid,i,j,e):
                                grid[i][j] = e
                                if solveSudoku(grid, i, j):
                                        return True                                
                                grid[i][j] = 0
                return False


        solveSudoku(sudoku)
        
        print(sudoku)
        t=str("{:.3}".format(time.clock()-t0))
        t = "运算时间:"+t+"秒."+" cd随风 用python语言编写"
        self.label_time.setText(t)


        self.lineEdit0.setText(str(sudoku[0][0]))
        self.lineEdit1.setText(str(sudoku[0][1]))
        self.lineEdit2.setText(str(sudoku[0][2]))
        self.lineEdit3.setText(str(sudoku[0][3]))
        self.lineEdit4.setText(str(sudoku[0][4]))
        self.lineEdit5.setText(str(sudoku[0][5]))
        self.lineEdit6.setText(str(sudoku[0][6]))
        self.lineEdit7.setText(str(sudoku[0][7]))
        self.lineEdit8.setText(str(sudoku[0][8]))
        self.lineEdit9.setText(str(sudoku[1][0]))
        self.lineEdit10.setText(str(sudoku[1][1]))
        self.lineEdit11.setText(str(sudoku[1][2]))
        self.lineEdit12.setText(str(sudoku[1][3]))
        self.lineEdit13.setText(str(sudoku[1][4]))
        self.lineEdit14.setText(str(sudoku[1][5]))
        self.lineEdit15.setText(str(sudoku[1][6]))
        self.lineEdit16.setText(str(sudoku[1][7]))
        self.lineEdit17.setText(str(sudoku[1][8]))
        self.lineEdit18.setText(str(sudoku[2][0]))
        self.lineEdit19.setText(str(sudoku[2][1]))
        self.lineEdit20.setText(str(sudoku[2][2]))
        self.lineEdit21.setText(str(sudoku[2][3]))
        self.lineEdit22.setText(str(sudoku[2][4]))
        self.lineEdit23.setText(str(sudoku[2][5]))
        self.lineEdit24.setText(str(sudoku[2][6]))
        self.lineEdit25.setText(str(sudoku[2][7]))
        self.lineEdit26.setText(str(sudoku[2][8]))
        self.lineEdit27.setText(str(sudoku[3][0]))
        self.lineEdit28.setText(str(sudoku[3][1]))
        self.lineEdit29.setText(str(sudoku[3][2]))
        self.lineEdit30.setText(str(sudoku[3][3]))
        self.lineEdit31.setText(str(sudoku[3][4]))
        self.lineEdit32.setText(str(sudoku[3][5]))
        self.lineEdit33.setText(str(sudoku[3][6]))
        self.lineEdit34.setText(str(sudoku[3][7]))
        self.lineEdit35.setText(str(sudoku[3][8]))
        self.lineEdit36.setText(str(sudoku[4][0]))
        self.lineEdit37.setText(str(sudoku[4][1]))
        self.lineEdit38.setText(str(sudoku[4][2]))
        self.lineEdit39.setText(str(sudoku[4][3]))
        self.lineEdit40.setText(str(sudoku[4][4]))
        self.lineEdit41.setText(str(sudoku[4][5]))
        self.lineEdit42.setText(str(sudoku[4][6]))
        self.lineEdit43.setText(str(sudoku[4][7])) 
        self.lineEdit44.setText(str(sudoku[4][8])) 
        self.lineEdit45.setText(str(sudoku[5][0])) 
        self.lineEdit46.setText(str(sudoku[5][1])) 
        self.lineEdit47.setText(str(sudoku[5][2])) 
        self.lineEdit48.setText(str(sudoku[5][3])) 
        self.lineEdit49.setText(str(sudoku[5][4])) 
        self.lineEdit50.setText(str(sudoku[5][5])) 
        self.lineEdit51.setText(str(sudoku[5][6])) 
        self.lineEdit52.setText(str(sudoku[5][7])) 
        self.lineEdit53.setText(str(sudoku[5][8])) 
        self.lineEdit54.setText(str(sudoku[6][0])) 
        self.lineEdit55.setText(str(sudoku[6][1])) 
        self.lineEdit56.setText(str(sudoku[6][2])) 
        self.lineEdit57.setText(str(sudoku[6][3])) 
        self.lineEdit58.setText(str(sudoku[6][4])) 
        self.lineEdit59.setText(str(sudoku[6][5])) 
        self.lineEdit60.setText(str(sudoku[6][6])) 
        self.lineEdit61.setText(str(sudoku[6][7])) 
        self.lineEdit62.setText(str(sudoku[6][8])) 
        self.lineEdit63.setText(str(sudoku[7][0])) 
        self.lineEdit64.setText(str(sudoku[7][1])) 
        self.lineEdit65.setText(str(sudoku[7][2])) 
        self.lineEdit66.setText(str(sudoku[7][3])) 
        self.lineEdit67.setText(str(sudoku[7][4])) 
        self.lineEdit68.setText(str(sudoku[7][5])) 
        self.lineEdit69.setText(str(sudoku[7][6])) 
        self.lineEdit70.setText(str(sudoku[7][7])) 
        self.lineEdit71.setText(str(sudoku[7][8])) 
        self.lineEdit72.setText(str(sudoku[8][0])) 
        self.lineEdit73.setText(str(sudoku[8][1])) 
        self.lineEdit74.setText(str(sudoku[8][2])) 
        self.lineEdit75.setText(str(sudoku[8][3])) 
        self.lineEdit76.setText(str(sudoku[8][4])) 
        self.lineEdit77.setText(str(sudoku[8][5])) 
        self.lineEdit78.setText(str(sudoku[8][6])) 
        self.lineEdit79.setText(str(sudoku[8][7])) 
        self.lineEdit80.setText(str(sudoku[8][8])) 
        
        
if __name__ == '__main__':
    app = QApplication(sys.argv)
    myWin = MyWindow()
    myWin.show()    
    sys.exit(app.exec_())

